src/books/urls.py
from django.urls import path
from .views import BookTitleListView, book_title_detail

app_name = 'books'

urlpatterns = [
    path('', BookTitleListView.as_view(), {'letter': None}, name='main'),
    path('<str:letter>/', BookTitleListView.as_view(), name='main'),
    path('<pk>/', book_title_detail, name='detail'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view, change_theme

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('switch/', change_theme, name='change'),
    path('books/', include('books.urls', namespace='books')),
    path("__reload__/", include("django_browser_reload.urls")),  
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Book Rental Administration"
admin.site.index_title = "Manage Book Rental System"

src/templates/layout/navbar.html
<nav class="fixed flex items-center h-16 bg-gradient-to-r from-cyan-500 to-blue-700 mb-2 w-full z-10 text-white">
    <div class="flex justify-between items-center w-full px-4 py-3">
        <div>
            logo
        </div>
        <div>
            avatar & menu
        </div>
    </div>
</nav>

src/templates/layout/sidebar.html
{% url "home" as path_to_home %}
{% url "books:main" as path_to_books %}

<aside class="hidden md:block sticky bg-slate-900 h-screen text-white w-full pt-24 text-sm">
    <ul>
        <li class="mb-6 mx-auto">
            <a href="{{path_to_home}}" class="grid h-12 place-items-center cursor-pointer hover:text-slate-200 duration-300 text-slate-500 {% if request.path == path_to_home %}text-white{% endif %}">
                <i class="fa-solid fa-chart-pie fa-xl"></i>
                <p>dashboard</p>
            </a>
        </li>
        <li class="mb-6 mx-auto">
            <a href="{{path_to_books}}" class="grid h-12 place-items-center cursor-pointer hover:text-slate-200 duration-300 text-slate-500 {% if 'books' == request.resolver_match.view_name|slice:'0:5' %}text-white{% endif %}">
                <i class="fa-solid fa-book fa-xl"></i>
                <p>books</p>
            </a>
        </li>
    </ul>
</aside>